CREATE DATABASE cadastro;

USE cadastro;

CREATE TABLE usuarios (
	id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    idusuario VARCHAR(10) NOT NULL UNIQUE,
    senha VARCHAR(10) NOT NULL
);